<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Bolt.App</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Http.fs" />
    <Compile Include="Config.fs" />
    <Compile Include="Tokens.fs" />
    <Compile Include="ApiModels.fs" />
    <Compile Include="LowLevel.fs" />
    <Compile Include="BoltApi.fs" />
    <Compile Include="Program.fs" />
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.SystemTextJson" Version="1.4.36" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bolt.Infrastructure\Bolt.Infrastructure.fsproj" />
    <ProjectReference Include="..\Bolt.Models\Bolt.Models.fsproj" />
  </ItemGroup>

</Project>
