<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="BoltApi\Shared.fs"/>
        <Compile Include="BoltApi\PreviousOrder.fs"/>
        <Compile Include="BoltApi\ActivityHours.fs"/>
        <Compile Include="BoltApi\DriverProfile.fs"/>
        <Compile Include="BoltApi\History.fs"/>
        <Compile Include="BoltApi\PastOrderDetail.fs"/>
        <Compile Include="BoltApi\ScrapedData.fs"/>
        <Compile Include="Geo\District.fs"/>
        <Compile Include="Meteo.fs"/>
        <Compile Include="Ride.fs"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FSharp.SystemTextJson" Version="1.4.36"/>
    </ItemGroup>

</Project>
