<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="RideReportingSource.fs" />
        <Compile Include="DayReporting.fs" />
        <Compile Include="WeekReporting.fs" />
        <Compile Include="MonthReporting.fs" />
        <Compile Include="Calculations.fs" />
        <Compile Include="Plotting.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Bolt.Infrastructure\Bolt.Infrastructure.fsproj" />
      <ProjectReference Include="..\Bolt.Models\Bolt.Models.fsproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ScottPlot" Version="5.1.58" />
    </ItemGroup>

</Project>
