<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="Geo/DistrictAssignment.Tests.fs" />
        <Compile Include="PerRide1.Tests.fs" />
        <Compile Include="PerRide2.Tests.fs" />
        <Compile Include="RideClustering.Tests.fs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Bolt.ETL\Bolt.ETL.fsproj" />
        <ProjectReference Include="..\..\src\Bolt.Models\Bolt.Models.fsproj" />
    </ItemGroup>

</Project>
