<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Shared\Model.fs" />
    <Compile Include="Shared\RideTime.fs" />
    <Compile Include="Geo\DistrictAssignment.fs" />
    <Compile Include="Meteo\Model.fs" />
    <Compile Include="RideFactory.fs" />
    <Compile Include="Analytics\AnalyticsContracts.fs" />
    <Compile Include="Analytics\AnalyticsClient.fs" />
    <Compile Include="Analysis\PerRide1.fs" />
    <Compile Include="Analysis\PerRide2.fs" />
    <Compile Include="Analysis\PerHour.fs" />
    <Compile Include="Analysis\BasicStatistics.fs" />
    <Compile Include="Analysis\RideClustering.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bolt.Models\Bolt.Models.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="FSharp.SystemTextJson">
      <HintPath>..\..\..\.nuget\packages\fsharp.systemtextjson\1.4.36\lib\netstandard2.0\FSharp.SystemTextJson.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
