<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Logging.fs"/>
        <Compile Include="Serialization.fs"/>
        <Compile Include="storage\Constants.fs"/>
        <Compile Include="storage\Storage.fs" />
        <Compile Include="ces\TaskResultBuilder.fs"/>
        <Compile Include="ces\ResultBuilder.fs"/>
        <Compile Include="ces\OptionBuilder.fs"/>
        <Compile Include="Repository\PreviousOrderRepository.fs" />
        <Compile Include="Repository\OrderHistoryRepository.fs" />
        <Compile Include="Repository\PastOrderDetailRepository.fs" />
        <Compile Include="Repository\ActivityHoursRepository.fs" />
        <Compile Include="Repository\DriverProfileRepository.fs" />
        <Compile Include="Repository\DistrictsRepository.fs" />
        <Compile Include="Repository\MeteoRepository.fs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Bolt.Models\Bolt.Models.fsproj"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="FSharp.SystemTextJson">
            <HintPath>..\..\..\.nuget\packages\fsharp.systemtextjson\1.4.36\lib\netstandard2.0\FSharp.SystemTextJson.dll</HintPath>
        </Reference>
    </ItemGroup>

</Project>
